### ISSUE TITLE
Howt to get GTA-V data label

### ISSUE THREAD

**Issue by mjjdick** [oscarmcnulty/gta-3d-dataset#2]
Hi, I read your paper and found it seems you use depth image to generate lidar data. so, I was wondering how you get the accurate label? thx for your help!

**Comment by oscarmcnulty** [comment]
Hey, sorry for the delay in getting back to you. The labels are all based on object bounding boxes obtained directly from the game using the APIs in https://github.com/crosire/scripthookvdotnet. Some of the bounding boxes are not that tight (some vehicles in particular like the icecream van are really bad) but they generally worked well.
